{
  "comments": [
    {
      "key": {
        "uuid": "e6fa0137_328671c4",
        "filename": "lib/blob/bdev/blob_bdev.c",
        "patchSetId": 1
      },
      "lineNbr": 158,
      "author": {
        "id": 1011222
      },
      "writtenOn": "2017-12-04T21:52:01Z",
      "side": 1,
      "message": "should this return 0 or a real errno?\n\nI guess I\u0027m not sure why we should treat this as a success.  It seems that blobstore should really decide whether a failed unmap should have other consequences, instead of assuming here that a failed unmap has no other consequences",
      "revId": "124b916e6b4a9f921bb7df071058b19ba5fc59c2",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735",
      "unresolved": false
    }
  ]
}