{
  "comments": [
    {
      "key": {
        "uuid": "ec9ad81d_69dbc828",
        "filename": "module/blobfs/bdev/blobfs_bdev.c",
        "patchSetId": 20
      },
      "lineNbr": 162,
      "author": {
        "id": 1011222
      },
      "writtenOn": "2019-09-25T21:02:58Z",
      "side": 1,
      "message": "similar to previous patch - I think we should have this function return void, and call the cb_fn explicitly here when there is an error",
      "revId": "1351267b67d04af1c61caac450369ad46c90347f",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735",
      "unresolved": true
    }
  ]
}