{
  "comments": [
    {
      "key": {
        "uuid": "395a399b_a059cce5",
        "filename": "lib/bdev/bdev.c",
        "patchSetId": 3
      },
      "lineNbr": 640,
      "author": {
        "id": 1011218
      },
      "writtenOn": "2017-11-13T06:59:13Z",
      "side": 0,
      "message": "oh wow, shouldn\u0027t this be a part of _call_next_module_fini?\nthis can be called before the thread_msg had a chance to execute. we could call finish_complete from bdev.c:630 prematurely.",
      "range": {
        "startLine": 638,
        "startChar": 0,
        "endLine": 640,
        "endChar": 2
      },
      "revId": "2f2288485a53651cb8c90e8bc096592a41cb3303",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "da3f66f5_71c88dc3",
        "filename": "lib/bdev/bdev.c",
        "patchSetId": 3
      },
      "lineNbr": 640,
      "author": {
        "id": 1010531
      },
      "writtenOn": "2017-11-13T18:13:57Z",
      "side": 0,
      "message": "Yes - that\u0027s the bug. A quick fix would be to move this check into the event, like you said. I think my fix is the better one though - it doesn\u0027t send events and isn\u0027t recursive for synchronous modules.",
      "parentUuid": "395a399b_a059cce5",
      "range": {
        "startLine": 638,
        "startChar": 0,
        "endLine": 640,
        "endChar": 2
      },
      "revId": "2f2288485a53651cb8c90e8bc096592a41cb3303",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735",
      "unresolved": true
    }
  ]
}